### ISSUE TITLE
Home Template : Widget area too narrow

### ISSUE THREAD

**Issue by mybooking-es** [mybooking-es/mybooking-wp-theme#10]
The widget area is too narrow to show the selector form on desktop
![image](https://user-images.githubusercontent.com/26079013/77778877-fdbe7200-7051-11ea-9f5e-a2710535a009.png)
It also does not adapt on mobile (margins on both sides)
![image](https://user-images.githubusercontent.com/26079013/77779042-32cac480-7052-11ea-8218-155e0d29d2c3.png)

**Comment by cranca** [comment]
This behaviour is due to Bootstrap `.container` settings and `section` element wrapping widget box. I solved this with some extra CSS at *_home_header.scss* and *_form_selector.scss*.
