### ISSUE TITLE
The icon to select language is not visible on mobile.

### ISSUE THREAD

**Issue by MarcelReig** [mybooking-es/mybooking-wp-theme#17]
On mobile, the menu displayed is 100% high and the icon to select language is not visible.
If we take away height:100% it doesn't look so nice but it works.

modules > _nav.scss line 191

`  .navbar-collapse {
    display: table;
    width: 100%;
    height: 100vh;
  }`

**Comment by cranca** [comment]
That's related with issue #5 and all the navigation behaivour. I think we must to rethink it. In this sens, I suspect that flex options are involved.
