### ISSUE TITLE
Home page without menu shows the Logo or site title in the center on Desktop

### ISSUE THREAD

**Issue by mybooking-es** [mybooking-es/mybooking-wp-theme#5]
It's happening since the last update on 2020.03.02.

- Create an empty site
- Create a page with "Mybooking Home" template
- Preview on the browser

**Comment by cranca** [comment]
I tested it with no luck. Additionaly, it affects also to table view because menu is hidden into toggler and doesn't appear on this screen resolution. 

Seems related to flexbox but anythig I tried affects this behaivour. Maybe we need to refactorize this...

**Comment by mybooking-es** [comment]
![image](https://user-images.githubusercontent.com/26079013/77779616-1bd8a200-7053-11ea-9f6d-569038888d12.png)
It happens when there is no menu on top

**Comment by cranca** [comment]
Changes were rejected so I reopen this issue
