### ISSUE TITLE
Gutenberg support

### ISSUE THREAD

**Issue by cranca** [mybooking-es/mybooking-wp-theme#6]
One of the issues of using Gutenberg editor on Mybooking theme is the lack of support. It affects how blocks are show on frontend and editor and how them match or not the theme.

Actions:
- Add fullwidth support
- Add gutenberg-specific CSS

https://www.billerickson.net/getting-your-theme-ready-for-gutenberg/
https://www.elmastudio.de/en/get-your-wordpress-theme-gutenberg-ready/
https://github.com/WordPress/WordPress/blob/master/wp-content/themes/twentytwenty/assets/css/editor-style-block.css

**Comment by cranca** [comment]
Gutenberg full-width added

**Comment by cranca** [comment]
Gutenber also integrated on Custom Post Types

**Comment by mybooking-es** [comment]
Integrated editor style.
