### ISSUE TITLE
CSS changes on parent are not reflected on childs

### ISSUE THREAD

**Issue by cranca** [mybooking-es/mybooking-wp-theme#9]
If you make a change on parent's CSS and commit it, this is not reflected on child due parent's CSS is duplicated on child and you have to update twice. This is annoying and must be changed on future releases because makes parent-child scheme so ineficient. IMHO.

**Comment by mybooking-es** [comment]
It is right. We have done the same as Understrap. When changed the parent, the scss should be copied to the src/sass/theme folder.
